algoritmo "idade"
// Função :
// Autor :
// Data : 04/05/2023
// Seção de Declarações 
var
   ano,nasc,idade:inteiro
inicio
      escreva ("em que ano estamos?")
      leia (ano)
      escreva ("em que ano voce nasceu?")
      leia (nasc)    
      idade<-ano-nasc
      escreval("Em",ano,"voce tera ",idade,"anos ")
      
      se(idade>=21) entao
          escreval(" e já terá  atingido a maioridade")
      fimse
      
fimalgoritmo
