algoritmo "teste escopo"
// Função :
// Autor :
// Data : 10/05/2023
// Seção de Declarações
var
n:inteiro
procedimento parOuImpar(v:inteiro)
inicio
escreval(" o valor de v e",v)
se (v%2=0) entao
   escreval (" o numero ",v," e par")
senao
   escreval (" o numero ",v," e impar")
fimse
fimProcedimento
inicio
escreva (" digite um numero:")
leia (n)
parOuImpar(n)

escreval (" o valor de n e ",n)
fimalgoritmo
